spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

logging:
  level:
    org:
      springframework:
        jdbc: debug
    hello:
      board:
        repository: trace

# MyBatis
mybatis:
  type-aliases-package: hello.board.domain
  configuration:
    map-underscore-to-camel-case: true